services:

  web:
    build: ./web_app
    depends_on:
      - employee_app
      - manager_app
      - selenium
    ports:
      - "5173:5173"

  employee_app:
    build: ./employee_app
    ports:
      - "7070:7070"
    volumes:
      - db_data:/app/data

  manager_app:
    build: ./manager_app
    ports:
      - "9090:9090"
    volumes:
      - db_data:/app/data

 selenium:
  image: selenium/standalone-chromium:latest
  shm_size: "2gb"
  ports:
    - "4444:4444"
    - "7900:7900"

volumes:
  db_data:
