services:

  web:
    build: ./web_app
    depends_on:
      - employee_app
      - manager_app
    ports:
      - "5173:5173"

  employee_app:
    build: ./employee_app
    ports:
      - "7070:7070"
    volumes:
      - db_data:/app/data

  manager_app:
    build: ./manager_app
    ports:
      - "9090:9090"
    volumes:
      - db_data:/app/data

  java_tests:
    image: maven:3.9-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./manager_app:/app
    depends_on:
      - manager_app
      - employee_app
    command: mvn test

  python_tests:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./employee_app:/app
    command: >
      sh -c "pip install -r requirements.txt &&
             pytest"

volumes:
  db_data:
