FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline -B

COPY src ./src


FROM build AS test

RUN mvn test -Dtest="*ControllerTest,*DaoTest"


FROM build AS package

RUN mvn package -DskipTests


FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

COPY --from=package /app/target/*.jar app.jar

EXPOSE 9090

CMD ["java", "-jar", "app.jar"]
