FROM python:3.12-slim AS base

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .


FROM base AS test

RUN pytest


FROM base AS runtime

EXPOSE 7070

CMD ["python", "app.py"]
